title: Maskym Cheremnov
description: Fullstack developer for web applications
baseurl: ""
url: https://mcheremnov.github.io/

theme: cvless

# site settings
taglong: Fullstack developer for web applications
tagshort: Personal website

# author settings
author:
  name: Maksym Cheremnov
  email: cheremnovmaksym@gmail.com
photo: assets/files/photo.jpeg
address: Ukraine, Odesa
phone: +380 732090252

# social media links
social:
  facebook: maximazimov
  x: cheremnovmaksym
  mastodon:
    user: username
    domain: mastodon.social 
  bluesky:
    user: username
    domain: bsky.social
  instagram: maximazimov
  linkedin: maksym-cheremnov-682585171
  xing: username
  stackoverflow: 0000000/username
  medium: username
  github: mcheremnov

# build settings
permalink: pretty
exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor/
  - docker-compose.yml

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never
  
