title: Maskym Cheremnov
description: Fullstack developer for web applications
baseurl: ""
url: https://mcheremnov.github.io/

theme: cvless

# site settings
taglong: Fullstack developer for web applications
tagshort: Personal website

# author settings
author:
  name: Maksym Cheremnov
  email: cheremnovmaksym@gmail.com
photo: assets/files/photo.jpeg
address: Ukraine, Odesa
phone: +380 732090252

# social media links
social:
  x: https://x.com/cheremnovmaksym
  instagram: https://www.instagram.com/maximazimov/
  linkedin: https://www.linkedin.com/in/maksym-cheremnov-682585171/
  github: https://github.com/mcheremnov

# build settings
permalink: pretty
exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor/
  - docker-compose.yml

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never
  
